# Generated by Django 3.0.2 on 2020-01-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandata',
            name='AvailableLoans',
            field=models.CharField(choices=[('Personal Loan', 'Personal Loan'), ('Home Loan', 'Home Loan'), ('Car Loan', 'Car Loan')], default='Personal Loan', max_length=20),
        ),
    ]
