# Generated by Django 3.0.2 on 2020-01-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0002_auto_20200121_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandata',
            name='id',
        ),
        migrations.AddField(
            model_name='loandata',
            name='LoanId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
