# Generated by Django 3.0.2 on 2020-01-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0003_auto_20200121_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandata',
            name='ApprovalStatus',
            field=models.BooleanField(default=False),
        ),
    ]
